### ISSUE TITLE
Repeats too often

### ISSUE THREAD

**Issue by CaptDread** [profelis/fz-sudoku#1]
So it repeats the same three digits (in different orders) along the vertical blocks. So like if there is three blocks that are 4 | 5 | 6, every where there is a 4, 5, or 6, the other two digits will be there on the same vertical line. Like 5 | 6 | 4  or  6 | 4 | 5.
Not a big issue just makes the game to easy.

**Comment by profelis** [comment]
fixed. will be much better in v1.1
