### ISSUE TITLE
Update the Sudoku app for the SDK version 0.100 f7

### ISSUE THREAD

**Issue by furippa** [profelis/fz-sudoku#2]
Hello!

Your Sudoku app version `1.1` fails to build with the SDK version `0.100.0-rc f7`. Please update the app in your repository and create a new pull request to the catalog repository with the updated manifest file.

> IMPORTANT: Don’t forget to update the app version and commit version in the manifest file.

[View logs](https://catalog.flipperzero.one/application/64e6b43a13043e71ea76675c/page)

Flipper Team

**Comment by profelis** [comment]
Fixed here https://github.com/flipperdevices/flipper-application-catalog/pull/320
